# syntax=docker/dockerfile:1
FROM debian:bookworm-slim AS builder

ENV LIBVIPS_VERSION 8.15.2
# sha256sum of tar.xz file on https://github.com/libvips/libvips/releases
ENV LIBVIPS_HASH a2ab15946776ca7721d11cae3215f20f1f097b370ff580cd44fc0f19387aee84

COPY ./build.sh /build.sh
RUN BUILD_TARGET=jpg_png /build.sh jpg_png

FROM debian:bookworm-slim
COPY --from=builder /vips /vips
