# syntax=docker/dockerfile:1
FROM debian:bookworm-slim AS builder

ENV LIBVIPS_VERSION 8.14.5
# sha256sum of tar.xz file on https://github.com/libvips/libvips/releases
ENV LIBVIPS_HASH 90374e9f6fbd5657b5faf306cacda20658d6144d385316b59b865bc1a487b68d

COPY ./build.sh /build.sh
RUN BUILD_TARGET=jpg_png /build.sh jpg_png

FROM debian:bookworm-slim
COPY --from=builder /vips /vips
