name: distribute

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        variant: [bookworm-jpg-png]
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        run: echo "VERSION=$(git describe --tags --match "v*" --always --abbrev=7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          push: true
          # TODO
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          file: Dockerfile.${{ matrix.variant }}
          tags: ghcr.io/cyberagentai/libvips:${{ matrix.variant }}-${{ env.VERSION }}

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
