name: distribute

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: "RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs: release
    strategy:
      fail-fast: false
      matrix:
        variant: [bookworm-jpg-png, trixie-jpg-png]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        run: echo "VERSION=$(git describe --tags --match "v*" --always --abbrev=7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.${{ matrix.variant }}
          cache-to: type=registry,ref=ghcr.io/cyberagentai/libvips-buildcache:${{ matrix.variant }}
          cache-from: type=registry,ref=ghcr.io/cyberagentai/libvips:${{ matrix.variant }}-buildcache
          tags: |
            ghcr.io/cyberagentai/libvips:${{ matrix.variant }}-${{ env.VERSION }}

concurrency:
  group: distribute-${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
